// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 20/2/2025, 17:05:31
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/plugins/**/*.{js,ts,mjs}","C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/composables/**/*.{js,ts,mjs}","C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/utils/**/*.{js,ts,mjs}","C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Taurai Munodawafa/OneDrive/Desktop/jobcard/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;